# This is a basic workflow that is manually triggered

name: 02 - Evento issue

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: 
  push: 
  issues: 
    types:
    - opened
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Hola Juancho
      run: echo "Hello ola Juancho"
